name: Pre-commit Checks

on:
  push:
    branches:
      - feature/*
      - fix/*
      - release/*

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the appropriate Python version

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install and configure tools
        run: |
          install_tool() {
            local tool_name="$1"
            local download_url=$(curl -s "https://api.github.com/repos/$2/releases/latest" | jq -r .assets[0].browser_download_url)
            local extension="${download_url##*.}"  # Get the file extension
            local temp_file="/tmp/$tool_name.$extension"
            
            curl -L "$download_url" -o "$temp_file"
            
            if [ "$extension" = "zip" ]; then
              unzip -q "$temp_file"
            else
              tar -xzf "$temp_file" && sudo mv "$tool_name" /usr/bin/
            fi
      
            rm "$temp_file"
          }

          install_tool "terraform-docs" "terraform-docs/terraform-docs"
          install_tool "tfupdate" "minamijoyo/tfupdate"
          install_tool "hcledit" "minamijoyo/hcledit"
          install_tool "tflint" "terraform-linters/tflint"

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-fixes by pre-commit"
          git push
